language: node_js
node_js:
  - "0.10"
services:
  - mongodb
before_install:
  - curl https://install.meteor.com | /bin/sh
  - npm install -g meteorite
before_script:
  - cd example/tests && npm install
script:
  - cd example && ./test
